version: "3"

services:
  bot:
    build:
      context: .
    init: true
    cap_add:
      - SYS_ADMIN
    environment:
      - FILES_FOLDER=/files
      - TARGET_URL=https://example.com
    volumes:
      - ./files:/files